name: build-deploy-1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # クローン
      - uses: actions/checkout@v4

      # nodeの使用準備
      - uses: actions/setup-node@v4
        id: setup_node
        with:
          node-version: 20.11.1

      # インストール
      - run: npm ci

      # アプリケーションのビルド
      - run: npm run build

      # アプリケーションをswaにdeploy
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOY_TOKEN }}
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          app_location: "dist"
          api_location: ""
